In [1]:
import torch

In [2]:
def inverse_2x2(matrix):
    det = matrix[0,0] * matrix[1,1] - matrix[0,1] * matrix[1,0]
    if det ==0:
        raise ValueError("Matrix is not invertible")
    inverse_det = 1.0/det
    inverse_matrix = torch.tensor([[matrix[1,1],-matrix[0,1]],[-matrix[1,0],matrix[0,0]]])
    inverse_matrix *= inverse_det
    return inverse_matrix

In [3]:
a = float(input("Enter a:"))
b = float(input("Enter b:"))
c = float(input("Enter c:"))
d = float(input("Enter d:"))

In [4]:
matrix_A = torch.tensor([[a,b],[c,d]])

In [5]:
try:
    inverse_A = inverse_2x2(matrix_A)
    print("Original Matrix A:")
    print(matrix_A)
    print("\nInverse of Matrix A:")
    print(inverse_A)
except ValueError as e:
    print("Error:",e)

Original Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Inverse of Matrix A:
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [13]:
def mat_mul(mat_a,mat_b):
    l = mat_a[0,0] * mat_b[0,0] + mat_a[0,1] * mat_b[1,0]
    m = mat_a[0,0] * mat_b[0,1] + mat_a[0,1] * mat_b[1,1]
    n = mat_a[1,0] * mat_b[0,0] + mat_a[1,1] * mat_b[1,0]
    o = mat_a[1,0] * mat_b[0,1] + mat_a[1,1] * mat_b[1,1]
    res_mat = torch.tensor([[l,m],[n,o]])
    return res_mat

In [16]:
matrix_B = torch.tensor([[5,6],[7,8]],dtype=torch.float32)
res_matrix = mat_mul(matrix_A,matrix_B)
print("Matrix Multiplication:")
print(res_matrix)

Matrix Multiplication:
tensor([[19., 22.],
        [43., 50.]])
