In [2]:
import torch

In [3]:
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[6,7],[8,9]])

In [4]:
res_add = torch.add(tensor1,tensor2)

print("Tensor Addition:")
print(res_add)

Tensor Addition:
tensor([[ 7,  9],
        [11, 13]])


In [5]:
res_mul = torch.mul(tensor1,tensor2)

print("Element-wise Multiplication:")
print(res_mul)

Element-wise Multiplication:
tensor([[ 6, 14],
        [24, 36]])


In [6]:
res_matmul = torch.mm(tensor1,tensor2)

print("Matrix Multiplication:")
print(res_matmul)

Matrix Multiplication:
tensor([[22, 25],
        [50, 57]])


In [7]:
res_transpose = torch.transpose(tensor1,0,1)

print("Transpose Operation:")
print(res_transpose)

Transpose Operation:
tensor([[1, 3],
        [2, 4]])


In [8]:
tensor = torch.tensor([[4,9],[16,25]],dtype=torch.float32)

res_sqrt = torch.sqrt(tensor)

print("Element-wise Square Root:")
print(res_sqrt)

Element-wise Square Root:
tensor([[2., 3.],
        [4., 5.]])


In [9]:
res_narrow = torch.narrow(tensor,1,1,1)

print("Narrow:")
print(res_narrow)

Narrow:
tensor([[ 9.],
        [25.]])


In [10]:
res_list = tensor1.tolist()

print("List:")
print(res_list)

List:
[[1, 2], [3, 4]]


In [11]:
tensor3 =torch.tensor([[[1,2,3],[4,5,6]]])
res_permutate = tensor3.permute(2,1,0)

print("Permutate:")
print(res_permutate)

Permutate:
tensor([[[1],
         [4]],

        [[2],
         [5]],

        [[3],
         [6]]])


In [13]:
res_sine = torch.sin(tensor)
print("Sine:")
print(res_sine)

Sine:
tensor([[-0.7568,  0.4121],
        [-0.2879, -0.1324]])


In [14]:
res_cosine = torch.cos(tensor)
print("Cosine:")
print(res_cosine)

Cosine:
tensor([[-0.6536, -0.9111],
        [-0.9577,  0.9912]])


In [15]:
res_tan = torch.tan(tensor)
print("Tangent:")
print(res_tan)

Tangent:
tensor([[ 1.1578, -0.4523],
        [ 0.3006, -0.1335]])
